# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-project:
  
    runs-on: ubuntu-latest
    
    steps:
  
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package install --file pom.xml
      
    - name: Upload API Jar
    - uses: actions/upload-artifcat@v2
      with:
        name: dispatch-api
        path: target/dispatch-api.jar
        
  release-project:
    
    runs-on: ubuntu-latest
    needs: build-project
    
    steps:
    - uses: actions/download-artificaft@v2
    - name: Download API Jar
      id: download_jar
      with:
        name: dispatch-api
        
    - uses: actions/checkout@v2
    - name: Bump version tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
   
   - uses: ncipollo/release-action@v1
    - name: Create a GitHub release
      id: create_release
      with:
        default_bump: false
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
       
    - uses: actions/upload-release-asset@v1
    - name: Upload Release API asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dispatch-api.jar
        asset_name: dispatch-api-${{ steps.tag_version.outputs.new_tag }}
        asset_content_type: application/jar
